"""change  scans column from 5 to 3 scans in the user

Revision ID: 4037a03cd133
Revises: aae6f249d087
Create Date: 2026-04-24 06:26:27.958023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4037a03cd133'
down_revision: Union[str, Sequence[str], None] = 'aae6f249d087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
