"""change  scans column from 5 to 3 scans in the user

Revision ID: aae6f249d087
Revises: aecf8a6a9bf9
Create Date: 2026-04-24 06:25:56.323828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae6f249d087'
down_revision: Union[str, Sequence[str], None] = 'aecf8a6a9bf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
