"""added scans column in the user

Revision ID: aecf8a6a9bf9
Revises: bcfdc09b3d9d
Create Date: 2026-04-23 02:33:11.838619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aecf8a6a9bf9'
down_revision: Union[str, Sequence[str], None] = 'bcfdc09b3d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('scans_remaining', sa.Integer(), server_default='3', nullable=False))
    op.add_column('users', sa.Column('last_replenished_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_replenished_at')
    op.drop_column('users', 'scans_remaining')
    # ### end Alembic commands ###
